from polybar import util

# Weather
fa_wind                             = util.surrogatepass('\uef16')
md_weather_cloudy                   = util.surrogatepass('\udb81\udd90')
md_weather_hazy                     = util.surrogatepass('\udb83\udf30')
md_weather_night                    = util.surrogatepass('\udb81\udd94')
md_weather_night_partly_cloudy      = util.surrogatepass('\udb83\udf31')
md_weather_partly_cloudy            = util.surrogatepass('\udb81\udd95')
md_weather_partly_rainy             = util.surrogatepass('\udb83\udf33')
md_weather_partly_snowy             = util.surrogatepass('\udb83\udf34')
md_weather_partly_snowy_rainy       = util.surrogatepass('\udb83\udf35')
md_weather_snowy                    = util.surrogatepass('\udb81\udd98')
md_weather_snowy_heavy              = util.surrogatepass('\udb83\udf36')
md_weather_snowy_rainy              = util.surrogatepass('\udb81\ude7f')
md_weather_sunny                    = util.surrogatepass('\uf185')
weather_day_cloudy                  = util.surrogatepass('\ue302')
weather_day_rain                    = util.surrogatepass('\ue308')
weather_day_showers                 = util.surrogatepass('\ue309')
weather_day_sleet                   = util.surrogatepass('\ue3aa')
weather_day_sleet_storm             = util.surrogatepass('\ue362')
weather_day_snow                    = util.surrogatepass('\ue30a')
weather_day_snow_thunderstorm       = util.surrogatepass('\ue365')
weather_day_snow_wind               = util.surrogatepass('\ue35f')
weather_day_storm_showers           = util.surrogatepass('\ue30e')
weather_day_sunny_overcast          = util.surrogatepass('\ue30c')
weather_day_thunderstorm            = util.surrogatepass('\ue30f')
weather_moonrise                    = util.surrogatepass('\ue3c1')
weather_moonset                     = util.surrogatepass('\ue3c2')
weather_night_alt_sleet             = util.surrogatepass('\ue3ac')
weather_night_alt_sleet_storm       = util.surrogatepass('\ue364')
weather_night_alt_snow              = util.surrogatepass('\ue327')
weather_night_alt_snow_thunderstorm = util.surrogatepass('\ue367')
weather_night_alt_snow_wind         = util.surrogatepass('\ue361')
weather_night_cloudy                = util.surrogatepass('\ue32e')
weather_night_rain                  = util.surrogatepass('\ue333')
weather_night_showers               = util.surrogatepass('\ue334')
weather_night_sleet                 = util.surrogatepass('\ue3ab')
weather_night_sleet_storm           = util.surrogatepass('\ue363')
weather_night_snow                  = util.surrogatepass('\ue335')
weather_night_snow_thunderstorm     = util.surrogatepass('\ue366')
weather_night_snow_wind             = util.surrogatepass('\ue360')
weather_night_storm_showers         = util.surrogatepass('\ue337')
weather_night_thunderstorm          = util.surrogatepass('\ue338')
weather_sleet                       = util.surrogatepass('\ue3ad')
weather_snow_wind                   = util.surrogatepass('\ue35e')
weather_sunrise                     = util.surrogatepass('\ue34c')
weather_sunset                      = util.surrogatepass('\ue34d')

# WiFi
md_wifi_strength_1                  = util.surrogatepass('\udb82\udd1f')
md_wifi_strength_1_alert            = util.surrogatepass('\udb82\udd20')
md_wifi_strength_1_lock             = util.surrogatepass('\udb82\udd21')
md_wifi_strength_1_lock_open        = util.surrogatepass('\udb85\udecb')
md_wifi_strength_2                  = util.surrogatepass('\udb82\udd22')
md_wifi_strength_2_alert            = util.surrogatepass('\udb82\udd23')
md_wifi_strength_2_lock             = util.surrogatepass('\udb82\udd24')
md_wifi_strength_2_lock_open        = util.surrogatepass('\udb85\udecc')
md_wifi_strength_3                  = util.surrogatepass('\udb82\udd25')
md_wifi_strength_3_alert            = util.surrogatepass('\udb82\udd26')
md_wifi_strength_3_lock             = util.surrogatepass('\udb82\udd27')
md_wifi_strength_3_lock_open        = util.surrogatepass('\udb85\udecd')
md_wifi_strength_4                  = util.surrogatepass('\udb82\udd28')
md_wifi_strength_4_alert            = util.surrogatepass('\udb82\udd29')
md_wifi_strength_4_lock             = util.surrogatepass('\udb82\udd2a')
md_wifi_strength_4_lock_open        = util.surrogatepass('\udb85\udece')
md_wifi_strength_alert_outline      = util.surrogatepass('\udb82\udd2b')
md_wifi_strength_lock_open_outline  = util.surrogatepass('\udb85\udecf')
md_wifi_strength_lock_outline       = util.surrogatepass('\udb82\udd2c')
md_wifi_strength_off                = util.surrogatepass('\udb82\udd2d')
md_wifi_strength_off_outline        = util.surrogatepass('\udb82\udd2e')
md_wifi_strength_outline            = util.surrogatepass('\udb82\udd2f')

# Weather
cod_arrow_small_down = util.surrogatepass('\uea9d')
cod_arrow_small_up   = arrow_up = util.surrogatepass('\ueaa0')
cod_graph_line       = util.surrogatepass('\uebe2')

# CPU
oct_cpu       = util.surrogatepass('\uf4bc')
md_cpu_32_bit = util.surrogatepass('\udb83\udedf')
md_cpu_64_bit = util.surrogatepass('\udb83\udee0')

# Disk
md_harddisk = util.surrogatepass('\udb80\udeca')

# Memory
cod_arrow_swap = util.surrogatepass('\uebcb')
fa_memory      = util.surrogatepass('\uefc5')
md_memory      = util.surrogatepass('\udb80\udf5b')

# Speedtest
md_speedometer_slow   = util.surrogatepass('\udb83\udf86')
md_speedometer_medium = util.surrogatepass('\udb83\udf85')
md_speedometer_fast   = util.surrogatepass('\udb81\udcc5')

# Others
cod_package           = util.surrogatepass('\ueb29')
fa_arrow_rotate_right = util.surrogatepass('\uf01e')
md_package_variant    = util.surrogatepass('\udb80\udfd6')
md_timer_outline      = util.surrogatepass('\udb81\udd1b')

# Alerts
md_alert               = util.surrogatepass('\udb80\udc26')
md_network_off         = util.surrogatepass('\udb83\udc9b')
md_network_off_outline = util.surrogatepass('\udb83\udc9c')
oct_alert              = util.surrogatepass('\uf421')
