from polybar import util

md_weather_cloudy              = util.surrogatepass('\udb81\udd90')
md_weather_hazy                = util.surrogatepass('\udb83\udf30')
md_weather_night               = util.surrogatepass('\udb81\udd94')
md_weather_night_partly_cloudy = util.surrogatepass('\udb83\udf31')
md_weather_partly_cloudy       = util.surrogatepass('\udb81\udd95')
md_weather_partly_rainy        = util.surrogatepass('\udb83\udf33')
md_weather_partly_snowy        = util.surrogatepass('\udb83\udf34')
md_weather_sunny               = util.surrogatepass('\uf185')
weather_day_cloudy             = util.surrogatepass('\ue302')
weather_day_rain               = util.surrogatepass('\ue308')
weather_day_showers            = util.surrogatepass('\ue309')
weather_day_sleet              = util.surrogatepass('\ue3aa')
weather_day_sleet_storm        = util.surrogatepass('\ue362')
weather_day_snow               = util.surrogatepass('\ue30a')
weather_day_storm_showers      = util.surrogatepass('\ue30e')
weather_day_sunny_overcast     = util.surrogatepass('\ue30c')
weather_night_alt_sleet        = util.surrogatepass('\ue3ac')
weather_night_alt_sleet_storm  = util.surrogatepass('\ue364')
weather_night_cloudy           = util.surrogatepass('\ue32e')
weather_night_rain             = util.surrogatepass('\ue333')
weather_night_showers          = util.surrogatepass('\ue334')
weather_night_sleet            = util.surrogatepass('\ue3ab')
weather_night_sleet_storm      = util.surrogatepass('\ue363')
weather_night_snow             = util.surrogatepass('\ue335')
weather_night_storm_showers    = util.surrogatepass('\ue337')
weather_sleet                  = util.surrogatepass('\ue3ad')